apiVersion: v1
kind: PersistentVolume
metadata:
  name: privatelinuxhost1-pv1
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/sdf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/workername
          operator: In
          values:
          - privatelinuxhost1